### ISSUE TITLE
Questions about data

### ISSUE THREAD

**Issue by ChasionNo1** [Darth-Kronos/Spectrum-Sensing#1]
Thank you for your excellent work. I have a few doubts about the datasets and hope to be answered.
1）There are different SNR changes in the results of your paper. I want to know how to get data with different SNR in datasets 1 and 2.
2）Does ‘fmnoise.csv’ represent noise data? What is its dimension?

**Comment by Darth-Kronos** [comment]
1) To evaluate the performance of the model for different SNRs, we first normalize the signal (subtract the mean and then divide by standard deviation) and multiple by the square root of SNR. This makes the signal zero mean and will have a variance = SNR. 

2) Yes, fmnoise.csv represents noise samples taken from an empty FM channel. The first column is the index and the subsequent columns represent the noise samples at a particular frequency.

**Comment by ChasionNo1** [comment]
Thanks for your answer！
